apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-hello
  labels:
    app: hello
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hello.type }}
  selector:
    app: hello
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.hello.ports | toYaml | nindent 2 -}}